In [62]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

driver_path = 'C:/Users/s_liouxe/Desktop/home-data-for-ml-course/'
train = pd.read_csv(driver_path + 'train.csv')
test = pd.read_csv(driver_path + 'test.csv')
submission = pd.read_csv(driver_path + 'sample_submission.csv')

In [2]:
train.shape, test.shape

((1460, 81), (1459, 80))

In [3]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     1443 non-null   object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [7]:
# columns 개수 달라서 두 데이터 비교

train_lst = train.columns.to_list()
test_lst = test.columns.to_list()

print(set(train_lst) - set(test_lst))
print(set(test_lst) - set(train_lst))

# 가격 test의 경우 가격 columns 만 추가됨

{'SalePrice'}
set()

In [8]:
# 결측치 n건 이하 column 삭제

column_cnt = []
for i in train_lst:
    if train[i].isnull().sum(axis=0) != 0:
        column_cnt.append(i)
        
print(column_cnt)
print(len(column_cnt))

['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature']
19

In [9]:
# 결측치 n건 이하 column 삭제

column_cnt2 = []
for i in test_lst:
    if test[i].isnull().sum(axis=0) != 0:
        column_cnt2.append(i)
        
print(column_cnt2)
print(len(column_cnt2))

['MSZoning', 'LotFrontage', 'Alley', 'Utilities', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType']
33

In [10]:
# print(set(column_cnt) - set(column_cnt2))
# print(set(column_cnt2) - set(column_cnt))

new_cnt = list(set(column_cnt + column_cnt2))
new_cnt2 = list(set(train_lst) - set(new_cnt))

In [11]:
train_n = train.drop(new_cnt, axis=1)
test_n = test.drop(new_cnt, axis=1)

In [12]:
train_n

,Id,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition,SalePrice
0,1,60,8450,Pave,Reg,Lvl,Inside,Gtl,CollgCr,Norm,...,61,0,0,0,0,0,2,2008,Normal,208500
1,2,20,9600,Pave,Reg,Lvl,FR2,Gtl,Veenker,Feedr,...,0,0,0,0,0,0,5,2007,Normal,181500
2,3,60,11250,Pave,IR1,Lvl,Inside,Gtl,CollgCr,Norm,...,42,0,0,0,0,0,9,2008,Normal,223500
3,4,70,9550,Pave,IR1,Lvl,Corner,Gtl,Crawfor,Norm,...,35,272,0,0,0,0,2,2006,Abnorml,140000
4,5,60,14260,Pave,IR1,Lvl,FR2,Gtl,NoRidge,Norm,...,84,0,0,0,0,0,12,2008,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,7917,Pave,Reg,Lvl,Inside,Gtl,Gilbert,Norm,...,40,0,0,0,0,0,8,2007,Normal,175000
1456,1457,20,13175,Pave,Reg,Lvl,Inside,Gtl,NWAmes,Norm,...,0,0,0,0,0,0,2,2010,Normal,210000
1457,1458,70,9042,Pave,Reg,Lvl,Inside,Gtl,Crawfor,Norm,...,60,0,0,0,0,2500,5,2010,Normal,266500
1458,1459,20,9717,Pave,Reg,Lvl,Inside,Gtl,NAmes,Norm,...,0,112,0,0,0,0,4,2010,Normal,142125
1459,1460,20,9937,Pave,Reg,Lvl,Inside,Gtl,Edwards,Norm,...,68,0,0,0,0,0,6,2008,Normal,147500

In [39]:
for i in new_cnt2:
    print("===== {} =====".format(i))
    print(train_n[i].value_counts())

===== PoolArea =====
0      1453
480       1
512       1
519       1
555       1
576       1
648       1
738       1
Name: PoolArea, dtype: int64
===== ExterCond =====
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: ExterCond, dtype: int64
===== YearBuilt =====
2006    67
2005    64
2004    54
2007    49
2003    45
        ..
1904     1
1898     1
1893     1
1882     1
2010     1
Name: YearBuilt, Length: 112, dtype: int64
===== HouseStyle =====
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64
===== LandSlope =====
Gtl    1382
Mod      65
Sev      13
Name: LandSlope, dtype: int64
===== YearRemodAdd =====
1950    178
2006     97
2007     76
2005     73
2004     62
       ...
2010      6
1983      5
1986      5
1952      5
1951      4
Name: YearRemodAdd, Length: 61, dtype: int64
===== 1stFlrSF =====
864     25
1040    16
912     14
848     12
894     12
        ..
1061     1
1058     1
1051     1
1047     1
2046     1
Name: 1stFlrSF, Length: 753, dtype: int64
===== 3SsnPorch =====
0      1436
168       3
216       2
144       2
180       2
407       1
320       1
304       1
290       1
245       1
238       1
182       1
196       1
23        1
162       1
153       1
140       1
130       1
96        1
508       1
Name: 3SsnPorch, dtype: int64
===== OverallQual =====
5     397
6     374
7     319
8     168
4     116
9      43
3      20
10     18
2       3
1       2
Name: OverallQual, dtype: int64
===== Id =====
1       1
982     1
980     1
979     1
978     1
       ..
485     1
484     1
483     1
482     1
1460    1
Name: Id, Length: 1460, dtype: int64
===== LandContour =====
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64
===== SalePrice =====
140000    20
135000    17
155000    14
145000    14
190000    13
          ..
337000     1
412500     1
306000     1
195400     1
206000     1
Name: SalePrice, Length: 663, dtype: int64
===== PavedDrive =====
Y    1340
N      90
P      30
Name: PavedDrive, dtype: int64
===== Condition2 =====
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
RRAn         1
RRAe         1
PosA         1
Name: Condition2, dtype: int64
===== OverallCond =====
5    821
6    252
7    205
8     72
4     57
3     25
9     22
2      5
1      1
Name: OverallCond, dtype: int64
===== YrSold =====
2009    338
2007    329
2006    314
2008    304
2010    175
Name: YrSold, dtype: int64
===== EnclosedPorch =====
0      1252
112      15
96        6
120       5
192       5
       ...
170       1
169       1
67        1
68        1
552       1
Name: EnclosedPorch, Length: 120, dtype: int64
===== MoSold =====
6     253
7     234
5     204
4     141
8     122
3     106
10     89
11     79
9      63
12     59
1      58
2      52
Name: MoSold, dtype: int64
===== HalfBath =====
0    913
1    535
2     12
Name: HalfBath, dtype: int64
===== OpenPorchSF =====
0      656
36      29
48      22
20      21
45      19
      ...
141      1
137      1
135      1
134      1
547      1
Name: OpenPorchSF, Length: 202, dtype: int64
===== WoodDeckSF =====
0      761
192     38
100     36
144     33
120     31
      ...
103      1
269      1
98       1
97       1
857      1
Name: WoodDeckSF, Length: 274, dtype: int64
===== LotArea =====
7200     25
9600     24
6000     17
8400     14
9000     14
         ..
13031     1
10991     1
8944      1
6897      1
8190      1
Name: LotArea, Length: 1073, dtype: int64
===== BldgType =====
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64
===== BedroomAbvGr =====
3    804
2    358
4    213
1     50
5     21
6      7
0      6
8      1
Name: BedroomAbvGr, dtype: int64
===== LowQualFinSF =====
0      1434
80        3
360       2
392       1
528       1
515       1
514       1
513       1
481       1
479       1
473       1
420       1
397       1
390       1
53        1
384       1
371       1
234       1
232       1
205       1
156       1
144       1
120       1
572       1
Name: LowQualFinSF, dtype: int64
===== Neighborhood =====
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
Blmngtn     17
MeadowV     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64
===== Fireplaces =====
0    690
1    650
2    115
3      5
Name: Fireplaces, dtype: int64
===== MSSubClass =====
20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: MSSubClass, dtype: int64
===== Heating =====
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: Heating, dtype: int64
===== RoofStyle =====
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: RoofStyle, dtype: int64
===== CentralAir =====
Y    1365
N      95
Name: CentralAir, dtype: int64
===== KitchenAbvGr =====
1    1392
2      65
3       2
0       1
Name: KitchenAbvGr, dtype: int64
===== SaleCondition =====
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: SaleCondition, dtype: int64
===== Street =====
Pave    1454
Grvl       6
Name: Street, dtype: int64
===== RoofMatl =====
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Roll          1
Membran       1
ClyTile       1
Metal         1
Name: RoofMatl, dtype: int64
===== TotRmsAbvGrd =====
6     402
7     329
5     275
8     187
4      97
9      75
10     47
11     18
3      17
12     11
2       1
14      1
Name: TotRmsAbvGrd, dtype: int64
===== HeatingQC =====
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: HeatingQC, dtype: int64
===== GrLivArea =====
864     22
1040    14
894     11
848     10
1456    10
        ..
2792     1
2794     1
1349     1
1347     1
2054     1
Name: GrLivArea, Length: 861, dtype: int64
===== LotShape =====
Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64
===== LotConfig =====
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64
===== MiscVal =====
0        1408
400        11
500         8
700         5
450         4
600         4
2000        4
480         2
1200        2
2500        1
350         1
560         1
54          1
620         1
8300        1
800         1
1150        1
15500       1
1300        1
1400        1
3500        1
Name: MiscVal, dtype: int64
===== 2ndFlrSF =====
0       829
728      10
504       9
672       8
546       8
       ...
812       1
811       1
473       1
475       1
1872      1
Name: 2ndFlrSF, Length: 417, dtype: int64
===== Condition1 =====
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: Condition1, dtype: int64
===== Foundation =====
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: Foundation, dtype: int64
===== ExterQual =====
TA    906
Gd    488
Ex     52
Fa     14
Name: ExterQual, dtype: int64
===== FullBath =====
2    768
1    650
3     33
0      9
Name: FullBath, dtype: int64
===== ScreenPorch =====
0      1344
192       6
120       5
224       5
180       4
       ...
175       1
178       1
40        1
185       1
480       1
Name: ScreenPorch, Length: 76, dtype: int64

In [40]:
train_n2 = train_n.drop(['3SsnPorch', 'LowQualFinSF', 'PoolArea', 'Street','Condition2'], axis=1)
train_n2

,Id,MSSubClass,LotArea,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,BldgType,...,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,ScreenPorch,MiscVal,MoSold,YrSold,SaleCondition,SalePrice
0,1,60,8450,Reg,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,...,Y,0,61,0,0,0,2,2008,Normal,208500
1,2,20,9600,Reg,Lvl,FR2,Gtl,Veenker,Feedr,1Fam,...,Y,298,0,0,0,0,5,2007,Normal,181500
2,3,60,11250,IR1,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,...,Y,0,42,0,0,0,9,2008,Normal,223500
3,4,70,9550,IR1,Lvl,Corner,Gtl,Crawfor,Norm,1Fam,...,Y,0,35,272,0,0,2,2006,Abnorml,140000
4,5,60,14260,IR1,Lvl,FR2,Gtl,NoRidge,Norm,1Fam,...,Y,192,84,0,0,0,12,2008,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,7917,Reg,Lvl,Inside,Gtl,Gilbert,Norm,1Fam,...,Y,0,40,0,0,0,8,2007,Normal,175000
1456,1457,20,13175,Reg,Lvl,Inside,Gtl,NWAmes,Norm,1Fam,...,Y,349,0,0,0,0,2,2010,Normal,210000
1457,1458,70,9042,Reg,Lvl,Inside,Gtl,Crawfor,Norm,1Fam,...,Y,0,60,0,0,2500,5,2010,Normal,266500
1458,1459,20,9717,Reg,Lvl,Inside,Gtl,NAmes,Norm,1Fam,...,Y,366,0,112,0,0,4,2010,Normal,142125
1459,1460,20,9937,Reg,Lvl,Inside,Gtl,Edwards,Norm,1Fam,...,Y,736,68,0,0,0,6,2008,Normal,147500

In [41]:
text_lst = []

for i in train_n2:
    if train_n2[i].dtype != 'int64':
        text_lst.append(i)
        
train_n3 = train_n2.drop(text_lst, axis = 1)
train_n3

,Id,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,GrLivArea,...,TotRmsAbvGrd,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,ScreenPorch,MiscVal,MoSold,YrSold,SalePrice
0,1,60,8450,7,5,2003,2003,856,854,1710,...,8,0,0,61,0,0,0,2,2008,208500
1,2,20,9600,6,8,1976,1976,1262,0,1262,...,6,1,298,0,0,0,0,5,2007,181500
2,3,60,11250,7,5,2001,2002,920,866,1786,...,6,1,0,42,0,0,0,9,2008,223500
3,4,70,9550,7,5,1915,1970,961,756,1717,...,7,1,0,35,272,0,0,2,2006,140000
4,5,60,14260,8,5,2000,2000,1145,1053,2198,...,9,1,192,84,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,7917,6,5,1999,2000,953,694,1647,...,7,1,0,40,0,0,0,8,2007,175000
1456,1457,20,13175,6,6,1978,1988,2073,0,2073,...,7,2,349,0,0,0,0,2,2010,210000
1457,1458,70,9042,7,9,1941,2006,1188,1152,2340,...,9,2,0,60,0,0,2500,5,2010,266500
1458,1459,20,9717,5,6,1950,1996,1078,0,1078,...,5,0,366,0,112,0,0,4,2010,142125
1459,1460,20,9937,5,6,1965,1965,1256,0,1256,...,6,0,736,68,0,0,0,6,2008,147500

In [42]:
import seaborn as sns
import matplotlib.pyplot as plt

corrMat = train_n3.corr()
y_corr = corrMat['SalePrice']

y_corr = pd.DataFrame(y_corr)
y_corr.rename(columns={'SalePrice':'yCorr'}, inplace=True)

In [43]:
y_corr

                  yCorr
Id            -0.021917
MSSubClass    -0.084284
LotArea        0.263843
OverallQual    0.790982
OverallCond   -0.077856
YearBuilt      0.522897
YearRemodAdd   0.507101
1stFlrSF       0.605852
2ndFlrSF       0.319334
GrLivArea      0.708624
FullBath       0.560664
HalfBath       0.284108
BedroomAbvGr   0.168213
KitchenAbvGr  -0.135907
TotRmsAbvGrd   0.533723
Fireplaces     0.466929
WoodDeckSF     0.324413
OpenPorchSF    0.315856
EnclosedPorch -0.128578
ScreenPorch    0.111447
MiscVal       -0.021190
MoSold         0.046432
YrSold        -0.028923
SalePrice      1.000000

In [44]:
y_corr[y_corr['yCorr'] > abs(0.3)]

                 yCorr
OverallQual   0.790982
YearBuilt     0.522897
YearRemodAdd  0.507101
1stFlrSF      0.605852
2ndFlrSF      0.319334
GrLivArea     0.708624
FullBath      0.560664
TotRmsAbvGrd  0.533723
Fireplaces    0.466929
WoodDeckSF    0.324413
OpenPorchSF   0.315856
SalePrice     1.000000

In [58]:
final_value_train = list(y_corr[y_corr['yCorr'] > abs(0.3)].index) + ['Id']
final_value_test = list(y_corr[y_corr['yCorr'] > abs(0.3)].index) + ['Id']
final_value_test.remove('SalePrice')
final_value_test.remove('Id')
final_value_train.remove('Id')

final_value_test
final_value_train

['OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'WoodDeckSF',
 'OpenPorchSF',
 'SalePrice']

In [59]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [57]:
train_n4 = train_n3[final_value_train]
test_n4 = test[final_value_test]

X_train = train_n4.drop(['SalePrice'], axis=1)
y_train = train_n4['SalePrice']

X_test = test_n4.drop(['SalePrice'], axis=1)
y_test = test_n4['SalePrice'] 

test_n4

KeyError: "['SalePrice'] not in index"

In [64]:
X_train, X_test, y_train, y_test = train_test_split(train_n4, y_train, random_state=0)

NameError: name 'y_train' is not defined

In [22]:
reg = LinearRegression().fit(X_train, y)
print(reg.predict(X_train))

[208245.17828575 177968.5560973  220201.01976708 ... 241724.56160462
 135393.14161165 161736.30730837]

In [23]:
preds = linear_reg_model.predict(X_train)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
print(f'RMSLE, {rmsle(y, preds, True):4f}')